name: lingcaizhongli
on:
  workflow_dispatch:

  schedule:
    - cron: '48 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: lingcaizhongli
        env:
          cdntp4: ${{ secrets.cdntp4 }}
        run: |
          printf '%s' "$cdntp4" | jq -r .rmato2417 | /bin/bash
          printf '%s' "$t22" | jq -r .q7 | /bin/bash
          echo $cjl7 | jq -r .vfumb7588 | /bin/bash
          echo $ftaul9 | jq -r .iaoy601 | /bin/bash
          printf '%s' "$bs74" | jq -r .vseo9812 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: BmiNk1d7
          path: "*.zip"
          retention-days: 1
